-- =============================================
-- events 테이블 생성 (공지사항 notices와 동일한 구조)
-- Supabase Dashboard > SQL Editor에서 1회 실행
-- =============================================

CREATE TABLE IF NOT EXISTS public.events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ,
  title      TEXT NOT NULL,
  content    TEXT NOT NULL,
  is_pinned  BOOLEAN DEFAULT false,
  author     TEXT
);

-- 고정 우선 + 최신순 조회 인덱스
CREATE INDEX IF NOT EXISTS events_pinned_created_idx
ON public.events (is_pinned DESC, created_at DESC);

-- RLS 활성화
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- =============================================
-- 기존 정책 삭제 (중복 방지)
-- =============================================

DROP POLICY IF EXISTS "events_public_select" ON public.events;
DROP POLICY IF EXISTS "events_admin_insert" ON public.events;
DROP POLICY IF EXISTS "events_admin_update" ON public.events;
DROP POLICY IF EXISTS "events_admin_delete" ON public.events;

-- =============================================
-- 조회 : 누구나 가능
-- =============================================

CREATE POLICY "events_public_select"
ON public.events
FOR SELECT
USING (true);

-- =============================================
-- 작성 : 관리자만
-- =============================================

CREATE POLICY "events_admin_insert"
ON public.events
FOR INSERT
WITH CHECK (
  ((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text
);

-- =============================================
-- 수정 : 관리자만
-- =============================================

CREATE POLICY "events_admin_update"
ON public.events
FOR UPDATE
USING (
  ((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text
)
WITH CHECK (
  ((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text
);

-- =============================================
-- 삭제 : 관리자만
-- =============================================

CREATE POLICY "events_admin_delete"
ON public.events
FOR DELETE
USING (
  ((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text
);

-- =============================================
-- updated_at 자동 갱신 트리거
-- =============================================

CREATE OR REPLACE FUNCTION public.set_events_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_events_updated_at
ON public.events;

CREATE TRIGGER trg_events_updated_at
BEFORE UPDATE
ON public.events
FOR EACH ROW
EXECUTE FUNCTION public.set_events_updated_at();