-- =============================================
-- events 테이블 생성 (공지사항 notices와 동일한 구조)
-- Supabase Dashboard > SQL Editor에서 1회 실행
-- =============================================

CREATE TABLE IF NOT EXISTS public.events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ,
  title      TEXT NOT NULL,
  content    TEXT NOT NULL,
  is_pinned  BOOLEAN DEFAULT false,
  author     TEXT
);

-- 고정 우선 + 최신순 조회 인덱스
CREATE INDEX IF NOT EXISTS events_pinned_created_idx ON public.events (is_pinned DESC, created_at DESC);

-- RLS 활성화
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- 기존 정책 제거 후 재생성 (중복 에러 방지)
DROP POLICY IF EXISTS "events_public_select" ON public.events;
DROP POLICY IF EXISTS "events_admin_insert" ON public.events;
DROP POLICY IF EXISTS "events_admin_update" ON public.events;
DROP POLICY IF EXISTS "events_admin_delete" ON public.events;

-- 읽기: 비로그인 포함 전체 공개
CREATE POLICY "events_public_select" ON public.events
  FOR SELECT USING (true);

-- 쓰기/수정/삭제: 관리자·스태프만 (notices 정책과 동일 기준)
CREATE POLICY "events_admin_insert" ON public.events
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
        AND auth.users.raw_user_meta_data->>'role' IN ('admin', 'staff')
    )
  );

CREATE POLICY "events_admin_update" ON public.events
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
        AND auth.users.raw_user_meta_data->>'role' IN ('admin', 'staff')
    )
  );

CREATE POLICY "events_admin_delete" ON public.events
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
        AND auth.users.raw_user_meta_data->>'role' IN ('admin', 'staff')
    )
  );
