-- =============================================
-- event_banners 테이블 생성 (상단 이벤트 배너/티커용)
-- Supabase Dashboard > SQL Editor에서 1회 실행
-- events_setup.sql을 먼저 실행해야 함 (event_id FK 참조)
-- =============================================

CREATE TABLE IF NOT EXISTS public.event_banners (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  text       TEXT NOT NULL,
  link_url   TEXT,
  event_id   BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
  is_active  BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  starts_at  TIMESTAMPTZ,
  ends_at    TIMESTAMPTZ,
  show_cta   BOOLEAN DEFAULT false,
  cta_text   TEXT NOT NULL DEFAULT '자세히 보기 ▶'
);

-- 노출 순서 조회 인덱스
CREATE INDEX IF NOT EXISTS event_banners_sort_idx ON public.event_banners (sort_order ASC, created_at DESC);

-- RLS 활성화
ALTER TABLE public.event_banners ENABLE ROW LEVEL SECURITY;

-- 기존 정책 제거 후 재생성 (중복 에러 방지)
DROP POLICY IF EXISTS "event_banners_public_select" ON public.event_banners;
DROP POLICY IF EXISTS "event_banners_admin_insert" ON public.event_banners;
DROP POLICY IF EXISTS "event_banners_admin_update" ON public.event_banners;
DROP POLICY IF EXISTS "event_banners_admin_delete" ON public.event_banners;

-- 읽기: 비로그인 포함 전체 공개 (활성/노출기간 필터는 클라이언트에서 처리)
CREATE POLICY "event_banners_public_select" ON public.event_banners
  FOR SELECT USING (true);

-- 쓰기/수정/삭제: 관리자·스태프만 (notices/events 정책과 동일 기준)
CREATE POLICY "event_banners_admin_insert" ON public.event_banners
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
        AND auth.users.raw_user_meta_data->>'role' IN ('admin', 'staff')
    )
  );

CREATE POLICY "event_banners_admin_update" ON public.event_banners
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
        AND auth.users.raw_user_meta_data->>'role' IN ('admin', 'staff')
    )
  );

CREATE POLICY "event_banners_admin_delete" ON public.event_banners
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
        AND auth.users.raw_user_meta_data->>'role' IN ('admin', 'staff')
    )
  );
